"""
generate_data.py
================
Run this script ONCE to produce data.csv if it is missing.
It is also called automatically the first time app.py starts.

  python generate_data.py
"""

import pandas as pd
import numpy as np
import os

np.random.seed(42)

# ─────────────────────────────────────────────
# Raw movie catalogue (100 realistic titles)
# ─────────────────────────────────────────────
MOVIES = [
    # (title, year, director, cast, genre, rating, keywords, overview)
    ("Dilwale Dulhania Le Jayenge", 1995, "Aditya Chopra", "Shah Rukh Khan, Kajol, Amrish Puri, Farida Jalal",
     "Romance, Drama", 8.1, "love, family, london, india, wedding",
     "A young man and woman fall in love on a trip through Europe. Back home, obstacles abound."),
    ("Lagaan", 2001, "Ashutosh Gowariker", "Aamir Khan, Gracy Singh, Rachel Shelley, Paul Blackthorne",
     "Drama, Sport, Musical", 8.1, "cricket, british raj, village, tax, freedom",
     "Villagers in British India stake their freedom on a game of cricket against the British."),
    ("3 Idiots", 2009, "Rajkumar Hirani", "Aamir Khan, R. Madhavan, Sharman Joshi, Kareena Kapoor",
     "Comedy, Drama", 8.4, "college, engineering, friendship, education, pressure",
     "Two friends search for their long-lost companion who changed their lives with his zeal."),
    ("Taare Zameen Par", 2007, "Aamir Khan", "Aamir Khan, Darsheel Safary, Tisca Chopra, Vipin Sharma",
     "Drama", 8.4, "dyslexia, education, child, art, teacher",
     "An eight-year-old boy is thought to be lazy, but actually has dyslexia."),
    ("Dangal", 2016, "Nitesh Tiwari", "Aamir Khan, Fatima Sana Shaikh, Sanya Malhotra, Sakshi Tanwar",
     "Biography, Drama, Sport", 8.3, "wrestling, women, gold medal, father, champion",
     "Former wrestler Mahavir Singh Phogat trains his daughters to become world-class wrestlers."),
    ("PK", 2014, "Rajkumar Hirani", "Aamir Khan, Anushka Sharma, Sushant Singh Rajput, Boman Irani",
     "Comedy, Drama, Sci-Fi", 8.1, "alien, religion, god, satire, love",
     "An alien on Earth loses the device that can take him home and must trust a journalist to help."),
    ("Gully Boy", 2019, "Zoya Akhtar", "Ranveer Singh, Alia Bhatt, Siddhant Chaturvedi, Vijay Raaz",
     "Drama, Music", 7.9, "rap, mumbai, slum, dream, hip-hop",
     "A street rapper from Mumbai's slums rises against all odds to find his voice."),
    ("Andhadhun", 2018, "Sriram Raghavan", "Ayushmann Khurrana, Tabu, Radhika Apte, Anil Dhawan",
     "Thriller, Crime, Comedy", 8.3, "blind, piano, murder, twist, dark comedy",
     "A series of mysterious events changes the life of a pianist who pretends to be blind."),
    ("Article 15", 2019, "Anubhav Sinha", "Ayushmann Khurrana, Nassar, Manoj Pahwa, Kumud Mishra",
     "Crime, Drama, Thriller", 8.0, "caste, discrimination, police, law, india",
     "An IPS officer unearths caste discrimination while investigating the rape of two girls."),
    ("Queen", 2014, "Vikas Bahl", "Kangana Ranaut, Rajkummar Rao, Lisa Haydon, Mish Boyko",
     "Drama, Comedy", 8.1, "solo travel, europe, self-discovery, women, wedding",
     "A Delhi girl goes on her honeymoon alone after her fiancé calls off the wedding."),
    ("Tumbbad", 2018, "Rahi Anil Barve", "Sohum Shah, Jyoti Malshe, Anita Date, Mohammad Samad",
     "Horror, Fantasy, Thriller", 8.2, "greed, goddess, ancient, curse, gold",
     "A mythological story about a goddess who was the first to be born and forgotten."),
    ("Gangs of Wasseypur", 2012, "Anurag Kashyap", "Manoj Bajpayee, Nawazuddin Siddiqui, Richa Chadda",
     "Action, Crime, Drama", 8.2, "coal mafia, revenge, gangs, bihar, family",
     "A saga of crime and revenge spanning three generations in the coal mining town Dhanbad."),
    ("Dil Chahta Hai", 2001, "Farhan Akhtar", "Aamir Khan, Saif Ali Khan, Akshaye Khanna, Preity Zinta",
     "Comedy, Drama, Romance", 8.1, "friendship, goa, youth, love, coming-of-age",
     "Three inseparable best friends from college go their separate ways after graduation."),
    ("Zindagi Na Milegi Dobara", 2011, "Zoya Akhtar", "Hrithik Roshan, Farhan Akhtar, Abhay Deol, Katrina Kaif",
     "Comedy, Drama, Adventure", 8.2, "spain, road trip, friends, fear, life",
     "Three friends take a road trip through Spain confronting their deepest fears."),
    ("Swades", 2004, "Ashutosh Gowariker", "Shah Rukh Khan, Gayatri Joshi, Kishori Balal, Smit Sheth",
     "Drama", 7.9, "patriotism, nasa, village, water, return",
     "A NASA scientist returns to India to bring his nanny to America and rediscovers his roots."),
    ("Mughal-E-Azam", 1960, "K. Asif", "Dilip Kumar, Madhubala, Prithviraj Kapoor, Durga Khote",
     "Drama, Historical, Romance", 8.2, "mughal, empire, love, war, royal",
     "The Mughal prince Salim falls in love with the court dancer Anarkali."),
    ("Sholay", 1975, "Ramesh Sippy", "Dharmendra, Amitabh Bachchan, Hema Malini, Sanjeev Kumar",
     "Action, Adventure, Drama", 8.2, "dacoit, village, friendship, revenge, classic",
     "A retired police officer enlists two criminals to catch a bandit who terrorizes his village."),
    ("Deewar", 1975, "Yash Chopra", "Amitabh Bachchan, Shashi Kapoor, Nirupa Roy, Parveen Babi",
     "Action, Crime, Drama", 7.9, "brothers, crime, law, mother, smuggling",
     "Two brothers separated by fate end up on opposite sides of the law."),
    ("Rang De Basanti", 2006, "Rakeysh Omprakash Mehra", "Aamir Khan, Siddharth, R. Madhavan, Alice Patten",
     "Drama", 8.1, "patriotism, youth, revolution, history, friendship",
     "A documentary filmmaker recruits college students to re-enact India's freedom struggle."),
    ("Dev.D", 2009, "Anurag Kashyap", "Abhay Deol, Mahi Gill, Kalki Koechlin, Dibyendu Bhattacharya",
     "Drama, Romance", 8.0, "love, heartbreak, alcohol, dark, modern",
     "A modern retelling of Devdas where the protagonist is flawed and self-destructive."),
    ("Kapoor & Sons", 2016, "Shakun Batra", "Sidharth Malhotra, Alia Bhatt, Fawad Khan, Ratna Pathak Shah",
     "Drama", 7.8, "family, secrets, brothers, reunion, love",
     "Two brothers return home to their ailing grandfather and uncover family secrets."),
    ("Kahaani", 2012, "Sujoy Ghosh", "Vidya Balan, Parambrata Chattopadhyay, Nawazuddin Siddiqui",
     "Thriller, Mystery", 8.1, "kolkata, pregnant woman, missing husband, mystery, twist",
     "A pregnant woman travels to Kolkata to find her missing husband."),
    ("Pink", 2016, "Aniruddha Roy Chowdhury", "Amitabh Bachchan, Taapsee Pannu, Kirti Kulhari",
     "Crime, Drama, Thriller", 8.1, "women, consent, law, harassment, lawyer",
     "Three girls fight for justice after they are accused of attacking a man."),
    ("Masaan", 2015, "Neeraj Ghaywan", "Richa Chadda, Vicky Kaushal, Sanjay Mishra, Shweta Tripathi",
     "Drama, Romance", 8.2, "varanasi, grief, society, love, cremation",
     "Two parallel stories of love and loss set against the ghats of Varanasi."),
    ("Udaan", 2010, "Vikramaditya Motwane", "Rajat Barmecha, Ronit Roy, Ram Kapoor, Manjot Singh",
     "Drama", 8.2, "abusive father, poetry, dreams, escape, coming-of-age",
     "A 17-year-old is forced to work in a factory by his strict father but yearns to write."),
    ("Barfi!", 2012, "Anurag Basu", "Ranbir Kapoor, Priyanka Chopra, Ileana D'Cruz, Saurabh Shukla",
     "Comedy, Drama, Romance", 8.1, "deaf-mute, love, darjeeling, triangle, autism",
     "A deaf-mute man falls in love with two women and navigates life with a big heart."),
    ("Highway", 2014, "Imtiaz Ali", "Alia Bhatt, Randeep Hooda, Mahesh Balraj, Durgesh Kumar",
     "Drama, Adventure, Romance", 7.6, "kidnap, freedom, road, discovery, trauma",
     "A kidnapping victim finds unexpected freedom while traveling across India with her captor."),
    ("Rockstar", 2011, "Imtiaz Ali", "Ranbir Kapoor, Nargis Fakhri, Shammi Kapoor, Aditi Rao Hydari",
     "Drama, Music, Romance", 7.9, "music, heartbreak, rock, prague, soul",
     "A college boy's heart break turns him into a rockstar struggling with love and fame."),
    ("Lootera", 2013, "Vikramaditya Motwane", "Ranveer Singh, Sonakshi Sinha, Barun Sobti, Vikrant Massey",
     "Drama, Romance", 7.9, "1950s, zamindari, bengal, con, love",
     "Set in the 1950s, a con man falls for the daughter of a zamindar he is conning."),
    ("Dil Dhadakne Do", 2015, "Zoya Akhtar", "Ranveer Singh, Priyanka Chopra, Anil Kapoor, Shefali Shah",
     "Comedy, Drama", 7.5, "cruise, family, marriage, rich, freedom",
     "A dysfunctional family goes on a cruise vacation and confronts their hidden truths."),
    ("Bard of Blood", 2019, "Ribhu Dasgupta", "Emraan Hashmi, Vineet Kumar Singh, Sobhita Dhulipala",
     "Thriller, Action", 7.2, "spy, balochistan, cia, mission, shakespeare",
     "A disgraced spy is called back for a crucial mission in Balochistan."),
    ("Badlapur", 2015, "Sriram Raghavan", "Varun Dhawan, Nawazuddin Siddiqui, Huma Qureshi, Yami Gautam",
     "Action, Crime, Drama", 8.0, "revenge, grief, criminal, dark, obsession",
     "A man's wife and son are accidentally killed during a robbery and he seeks revenge 15 years later."),
    ("Newton", 2017, "Amit V. Masurkar", "Rajkummar Rao, Pankaj Tripathi, Anjali Patil, Raghubir Yadav",
     "Comedy, Drama, Satire", 7.6, "election, jungle, democracy, duty, tribal",
     "A government employee is assigned to conduct elections in a conflict-ridden region."),
    ("Stree", 2018, "Amar Kaushik", "Rajkummar Rao, Shraddha Kapoor, Pankaj Tripathi, Aparshakti Khurana",
     "Comedy, Horror", 7.7, "witch, ghost, small town, folklore, comedy",
     "A small town is terrorised by a supernatural entity that abducts men."),
    ("Bala", 2019, "Amar Kaushik", "Ayushmann Khurrana, Bhumi Pednekar, Yami Gautam",
     "Comedy, Drama", 7.2, "baldness, self-esteem, dark skin, comedy, love",
     "A young man with premature balding struggles with self-esteem and societal pressure."),
    ("Gulabo Sitabo", 2020, "Shoojit Sircar", "Amitabh Bachchan, Ayushmann Khurrana, Vijay Raaz",
     "Comedy, Drama", 6.9, "landlord, tenant, lucknow, haveli, greed",
     "A landlord and tenant clash over an old Lucknow haveli through clever schemes."),
    ("Shoojit Sircar's Vicky Donor", 2012, "Shoojit Sircar", "Ayushmann Khurrana, Yami Gautam, Annu Kapoor",
     "Comedy, Drama, Romance", 7.3, "sperm donor, infertility, comedy, family, marriage",
     "A sperm bank doctor convinces a charming man to become a sperm donor."),
    ("Uri: The Surgical Strike", 2019, "Aditya Dhar", "Vicky Kaushal, Yami Gautam, Paresh Rawal, Mohit Raina",
     "Action, Thriller, War", 8.2, "army, surgical strike, pakistan, revenge, mission",
     "The Indian army carries out a covert operation in response to an attack on their base."),
    ("Chhichhore", 2019, "Nitesh Tiwari", "Sushant Singh Rajput, Shraddha Kapoor, Varun Sharma, Prateik Babbar",
     "Comedy, Drama", 8.2, "college, friendship, failure, life lessons, reunion",
     "A group of friends revisit their college days to convince one of their sons to not give up."),
    ("Raazi", 2018, "Meghna Gulzar", "Alia Bhatt, Vicky Kaushal, Rajit Kapoor, Shishir Sharma",
     "Spy, Thriller, Drama", 7.8, "spy, kashmir, pakistan, 1971, patriotism",
     "A Kashmiri girl marries into a Pakistani military family for India during the 1971 war."),
    ("Talvar", 2015, "Meghna Gulzar", "Irrfan Khan, Konkona Sen Sharma, Neeraj Kabi, Sohum Shah",
     "Crime, Drama, Mystery", 8.0, "murder, investigation, double murder, justice, media",
     "An investigator reopens the double murder case of a doctor's daughter."),
    ("Piku", 2015, "Shoojit Sircar", "Amitabh Bachchan, Deepika Padukone, Irrfan Khan, Moushumi Chatterjee",
     "Comedy, Drama", 7.9, "father, daughter, road trip, kolkata, quirky",
     "A quirky daughter accompanies her eccentric father on a road trip from Delhi to Kolkata."),
    ("Drishyam", 2015, "Nishikant Kamat", "Ajay Devgn, Tabu, Shriya Saran, Ishita Dutta",
     "Thriller, Crime", 8.3, "alibi, murder, family, police, perfect crime",
     "A man fights to save his family after covering up a crime to protect them."),
    ("A Wednesday!", 2008, "Neeraj Pandey", "Naseeruddin Shah, Anupam Kher, Jimmy Sheirgill, Deepal Shaw",
     "Thriller, Crime", 8.3, "bomb threat, common man, terrorism, police, justice",
     "An anonymous common man plants bombs across Mumbai and demands four terrorists be released."),
    ("Special 26", 2013, "Neeraj Pandey", "Akshay Kumar, Manoj Bajpayee, Anupam Kher, Kajal Aggarwal",
     "Crime, Thriller", 7.7, "heist, cbi, fake officers, 1987, con",
     "A group of con men pose as CBI officers and rob prominent people."),
    ("Baby", 2015, "Neeraj Pandey", "Akshay Kumar, Rana Daggubati, Taapsee Pannu, Danny Denzongpa",
     "Action, Thriller", 7.3, "counter-terrorism, covert mission, isi, action, patriotism",
     "A top-secret counter-terrorism squad goes on a covert mission to eliminate threats."),
    ("Airlift", 2016, "Raja Krishna Menon", "Akshay Kumar, Nimrat Kaur, Purab Kohli, Prakash Belawadi",
     "Biography, Drama, Thriller", 7.9, "kuwait, evacuation, 1990, iraq, patriotism",
     "A wealthy businessman helps evacuate thousands of Indians stranded in Kuwait."),
    ("Rustom", 2016, "Tinu Suresh Desai", "Akshay Kumar, Ileana D'Cruz, Arjan Bajwa, Esha Gupta",
     "Crime, Drama, Romance", 6.8, "navy, murder, court martial, 1959, love",
     "A naval officer kills his wife's lover and must defend himself in a military court."),
    ("Kesari", 2019, "Anurag Singh", "Akshay Kumar, Parineeti Chopra, Mir Sarwar, Edward Sonnenblick",
     "Action, Drama, War", 7.3, "21 sikhs, battle of saragarhi, war, courage, history",
     "The story of 21 Sikh soldiers who fought against 10,000 Afghans in 1897."),
    ("Padmaavat", 2018, "Sanjay Leela Bhansali", "Deepika Padukone, Shahid Kapoor, Ranveer Singh, Jim Sarbh",
     "Action, Drama, Historical, Romance", 7.0, "rajput, queen, alauddin, honor, sacrifice",
     "Queen Padmaavati's honor is threatened by Sultan Alauddin Khilji."),
    ("Ram-Leela", 2013, "Sanjay Leela Bhansali", "Ranveer Singh, Deepika Padukone, Supriya Pathak, Richa Chadda",
     "Action, Drama, Romance", 7.3, "romeo juliet, gujarat, rival families, love, tragedy",
     "A modern retelling of Romeo and Juliet set in the Garasia community of Gujarat."),
    ("Bajirao Mastani", 2015, "Sanjay Leela Bhansali", "Ranveer Singh, Deepika Padukone, Priyanka Chopra",
     "Action, Drama, Historical, Romance", 7.2, "peshwa, maratha, love, war, honor",
     "The story of Maratha warrior Bajirao and his love for Mastani."),
    ("Devdas", 2002, "Sanjay Leela Bhansali", "Shah Rukh Khan, Aishwarya Rai, Madhuri Dixit, Jackie Shroff",
     "Drama, Romance", 7.5, "tragic love, alcohol, heartbreak, classic, kolkata",
     "A rich young man drinks himself to death after his childhood love marries another."),
    ("Hum Dil De Chuke Sanam", 1999, "Sanjay Leela Bhansali", "Salman Khan, Aishwarya Rai, Ajay Devgn",
     "Drama, Musical, Romance", 7.5, "love triangle, italy, music, forgiveness, india",
     "A woman married to one man struggles with feelings for another who truly loves her."),
    ("Black", 2005, "Sanjay Leela Bhansali", "Amitabh Bachchan, Rani Mukerji, Ayesha Kapoor, Shernaz Patel",
     "Drama", 8.1, "blind deaf mute, teacher, helen keller, india, inspiration",
     "A teacher is hired to educate a deaf-blind girl and change both their lives."),
    ("Mughal Saleem", 2023, "Ram Madhvani", "Aamir Khan, Kareena Kapoor, Ranveer Singh",
     "Drama, Historical", 7.4, "mughal, empire, akbar, succession, war",
     "A dramatic retelling of the Mughal succession wars."),
    ("Bhool Bhulaiyaa", 2007, "Priyadarshan", "Akshay Kumar, Vidya Balan, Shiney Ahuja, Paresh Rawal",
     "Comedy, Horror, Mystery", 7.4, "ghost, mansion, psychiatry, comedy, possession",
     "A psychiatrist is called to examine a woman believed to be possessed in a haunted mansion."),
    ("Golmaal: Fun Unlimited", 2006, "Rohit Shetty", "Ajay Devgn, Arshad Warsi, Shreyas Talpade, Tusshar Kapoor",
     "Comedy", 7.1, "blind couple, comedy, lies, friendship, fun",
     "Four friends trick a blind couple while living in their home and chaos ensues."),
    ("Singham", 2011, "Rohit Shetty", "Ajay Devgn, Kajal Aggarwal, Prakash Raj, Abhimanyu Singh",
     "Action, Drama", 7.6, "honest cop, politician, corruption, mass action",
     "An honest Goa police officer fights against a corrupt politician."),
    ("Ek Tha Tiger", 2012, "Kabir Khan", "Salman Khan, Katrina Kaif, Girish Karnad, Ranvir Shorey",
     "Action, Romance, Thriller", 6.7, "spy, isi, love, ira, agent",
     "A RAW agent falls for a woman who turns out to be a Pakistani spy."),
    ("Sultan", 2016, "Ali Abbas Zafar", "Salman Khan, Anushka Sharma, Amit Sadh, Randeep Hooda",
     "Action, Drama, Sport", 7.0, "wrestling, comeback, mma, family, redemption",
     "A wrestler makes a comeback after his personal life falls apart."),
    ("Tiger Zinda Hai", 2017, "Ali Abbas Zafar", "Salman Khan, Katrina Kaif, Paresh Rawal, Angad Bedi",
     "Action, Thriller", 6.6, "isi, isis, hostage rescue, iraq, mission",
     "Tiger and Zoya reunite to save Indian nurses held hostage by a terrorist group."),
    ("Bajrangi Bhaijaan", 2015, "Kabir Khan", "Salman Khan, Harshaali Malhotra, Kareena Kapoor, Nawazuddin Siddiqui",
     "Drama, Family", 8.1, "pakistan, child, lost, devotion, humanity",
     "A devoted man takes a mute Pakistani girl home after she gets lost in India."),
    ("Kabir Singh", 2019, "Sandeep Reddy Vanga", "Shahid Kapoor, Kiara Advani, Soham Majumdar, Arjan Bajwa",
     "Drama, Romance", 7.1, "love, jealousy, addiction, obsession, medical",
     "A brilliant surgeon falls into a self-destructive spiral after his love marries another."),
    ("Jab We Met", 2007, "Imtiaz Ali", "Shahid Kapoor, Kareena Kapoor, Tarun Arora, Dara Singh",
     "Comedy, Drama, Romance", 7.9, "train, punjab, runaway girl, heartbreak, love",
     "A depressed businessman meets an overly optimistic girl on a train and his life changes."),
    ("Love Aaj Kal", 2009, "Imtiaz Ali", "Saif Ali Khan, Deepika Padukone, Rishi Kapoor, Giselli Monteiro",
     "Comedy, Romance", 7.2, "modern love, old love, delhi, london, contrast",
     "Two love stories set in different eras explore the changing face of relationships."),
    ("Tamasha", 2015, "Imtiaz Ali", "Ranbir Kapoor, Deepika Padukone, Javed Sheikh, Piyush Mishra",
     "Drama, Romance", 7.5, "identity, storytelling, corsica, real self, rebellion",
     "A man and woman share a brief connection in Corsica, then meet years later in India."),
    ("Ae Dil Hai Mushkil", 2016, "Karan Johar", "Ranbir Kapoor, Anushka Sharma, Aishwarya Rai, Fawad Khan",
     "Drama, Romance", 6.9, "unrequited love, london, music, heartbreak, friendship",
     "A man falls for his best friend who doesn't love him back."),
    ("Kuch Kuch Hota Hai", 1998, "Karan Johar", "Shah Rukh Khan, Kajol, Rani Mukerji, Salman Khan",
     "Drama, Romance, Comedy", 7.4, "college, friendship, love triangle, reunion, family",
     "A college campus love story and its bittersweet reunion years later."),
    ("Kabhi Khushi Kabhie Gham", 2001, "Karan Johar", "Amitabh Bachchan, Jaya Bachchan, Shah Rukh Khan, Kajol",
     "Drama, Family, Romance", 7.4, "family, nri, tradition, reunion, london",
     "A man tries to reunite his estranged brother with their parents."),
    ("My Name Is Khan", 2010, "Karan Johar", "Shah Rukh Khan, Kajol, Jimmy Sheirgill, Sheetal Menon",
     "Drama, Romance", 7.8, "autism, 9/11, post-9/11, america, prejudice",
     "A Muslim man with Asperger's syndrome journeys across America to speak to the President."),
    ("Student of the Year", 2012, "Karan Johar", "Siddharth Malhotra, Varun Dhawan, Alia Bhatt, Rishi Kapoor",
     "Drama, Romance, Comedy", 5.8, "college, competition, love, friendship, youth",
     "Three friends compete for academic excellence and a love interest at a prestigious college."),
    ("Raanjhanaa", 2013, "Aanand L. Rai", "Dhanush, Sonam Kapoor, Abhay Deol, Swara Bhaskar",
     "Drama, Romance", 7.5, "varanasi, obsessive love, politics, rejection, sacrifice",
     "A boy from Varanasi falls obsessively in love with a girl visiting from the city."),
    ("Tanu Weds Manu", 2011, "Aanand L. Rai", "Kangana Ranaut, R. Madhavan, Jimmy Sheirgill, Deepak Dobriyal",
     "Comedy, Romance", 7.5, "arranged marriage, kanpur, quirky, love, friendship",
     "A quirky couple have an arranged marriage and navigate their very different personalities."),
    ("Tanu Weds Manu Returns", 2015, "Aanand L. Rai", "Kangana Ranaut, R. Madhavan, Jimmy Sheirgill",
     "Comedy, Romance", 7.7, "sequel, marriage, lookalike, kanpur, divorce",
     "The couple's marriage falls apart and the man finds a lookalike of his wife."),
    ("Raees", 2017, "Rahul Dholakia", "Shah Rukh Khan, Mahira Khan, Nawazuddin Siddiqui, Atul Kulkarni",
     "Action, Crime, Drama", 6.9, "bootlegger, gujarat, election, law, power",
     "A bootlegger rises to power in Gujarat while a dedicated cop hunts him."),
    ("Don", 2006, "Farhan Akhtar", "Shah Rukh Khan, Priyanka Chopra, Boman Irani, Isha Koppikar",
     "Action, Crime, Thriller", 7.3, "undercover, drug lord, look-alike, interpol, twist",
     "A cop recruits a criminal's lookalike to infiltrate a drug cartel."),
    ("Rock On!!", 2008, "Abhishek Kapoor", "Farhan Akhtar, Arjun Rampal, Purab Kohli, Luke Kenny",
     "Drama, Music", 7.7, "band, friendship, reunion, dreams, music",
     "A group of friends reunite to revive their rock band after personal setbacks."),
    ("Kai Po Che!", 2013, "Abhishek Kapoor", "Sushant Singh Rajput, Raj Kumar Yadav, Amit Sadh, Amrita Puri",
     "Drama, Sport", 7.9, "cricket, kite festival, friendship, gujarat, riot",
     "Three friends in Ahmedabad chase dreams of opening a sports academy amid political unrest."),
    ("M.S. Dhoni: The Untold Story", 2016, "Neeraj Pandey", "Sushant Singh Rajput, Kiara Advani, Disha Patani",
     "Biography, Drama, Sport", 8.0, "cricket, dhoni, captain, rags to riches, india",
     "The life story of Mahendra Singh Dhoni from a railway officer to India's cricket captain."),
    ("Sanju", 2018, "Rajkumar Hirani", "Ranbir Kapoor, Paresh Rawal, Anushka Sharma, Sonam Kapoor",
     "Biography, Drama, Comedy", 7.7, "sanjay dutt, drugs, akk, media, bollywood",
     "The biopic of Bollywood actor Sanjay Dutt covering his controversial life."),
    ("Biopics", 2020, "Shonali Bose", "Priyanka Chopra, Farhan Akhtar, Rohit Saraf, Shonali Bose",
     "Biography, Drama, Sport", 7.5, "duathlon, disability, determination, mother, marathon",
     "A Punjabi woman with a disability trains for a triathlon inspired by her son."),
    ("Shakuntala Devi", 2020, "Anu Menon", "Vidya Balan, Sanya Malhotra, Jisshu Sengupta, Amit Sadh",
     "Biography, Drama", 7.2, "mathematician, human computer, mother, daughter, london",
     "The true story of Shakuntala Devi, mathematical genius called the Human Computer."),
    ("Thappad", 2020, "Anubhav Sinha", "Taapsee Pannu, Pavail Gulati, Maya Sarao, Ratna Pathak Shah",
     "Drama", 7.7, "domestic violence, self-respect, marriage, women, slap",
     "A woman decides to divorce her husband after he slaps her at a party."),
    ("Gulaal", 2009, "Anurag Kashyap", "Raj Singh Chaudhary, Jesse Randhawa, Abhimanyu Singh, Aditya Srivastav",
     "Crime, Drama, Political", 7.7, "rajasthan, royalty, politics, election, revenge",
     "A student gets entangled in the political movement for an independent Rajputana."),
    ("Haider", 2014, "Vishal Bhardwaj", "Shahid Kapoor, Tabu, Shraddha Kapoor, Kay Kay Menon",
     "Drama, Thriller", 8.1, "kashmir, hamlet, shakespeare, disappearance, revenge",
     "Set in Kashmir, a man searches for his missing father and uncovers dark secrets."),
    ("Omkara", 2006, "Vishal Bhardwaj", "Ajay Devgn, Kareena Kapoor, Saif Ali Khan, Vivek Oberoi",
     "Crime, Drama, Thriller", 8.1, "othello, shakespeare, up, gangs, jealousy",
     "A gangster in Uttar Pradesh is manipulated by a jealous aide who destroys his relationship."),
    ("Maqbool", 2003, "Vishal Bhardwaj", "Irrfan Khan, Tabu, Pankaj Kapur, Naseeruddin Shah",
     "Crime, Drama, Thriller", 7.9, "macbeth, shakespeare, mumbai mafia, love, ambition",
     "A Mumbai don's loyal henchman falls for his boss's mistress and is persuaded to kill him."),
    ("Paan Singh Tomar", 2012, "Tigmanshu Dhulia", "Irrfan Khan, Mahi Gill, Nawazuddin Siddiqui",
     "Biography, Drama, Action", 8.2, "athlete, rebel, dacoit, steeplechase, system",
     "A national steeplechase champion becomes a dacoit after being failed by the system."),
    ("Lunch Box", 2013, "Ritesh Batra", "Irrfan Khan, Nimrat Kaur, Nawazuddin Siddiqui, Bharati Achrekar",
     "Drama, Romance", 7.8, "dabbawalas, letters, loneliness, mumbai, connection",
     "A mistakenly-delivered lunchbox creates an unlikely bond between a stranger and a widow."),
    ("Badminton", 2023, "Nikkhil Advani", "Ranveer Singh, Deepika Padukone, Jim Sarbh",
     "Drama, Sport", 6.8, "badminton, childhood, comeback, rivalry, sport",
     "A badminton prodigy returns after injury to compete one last time."),
    ("Shershaah", 2021, "Vishnuvardhan", "Sidharth Malhotra, Kiara Advani, Shiv Panditt, Raj Arjun",
     "Action, Biography, Drama, War", 8.4, "kargil, captain vikram batra, war, love, army",
     "The story of Captain Vikram Batra, Param Vir Chakra awardee in the Kargil War."),
    ("83", 2021, "Kabir Khan", "Ranveer Singh, Deepika Padukone, Pankaj Tripathi, Tahir Raj Bhasin",
     "Biography, Drama, Sport", 7.9, "1983 world cup, kapil dev, cricket, india, victory",
     "The story of India's historic 1983 Cricket World Cup win under Kapil Dev."),
    ("RRR", 2022, "S.S. Rajamouli", "N.T. Rama Rao Jr., Ram Charan, Alia Bhatt, Ajay Devgn",
     "Action, Drama, Historical", 8.0, "bheem, alluri, british raj, friendship, freedom",
     "A fictional account of a friendship between two Indian revolutionaries in the 1920s."),
    ("Pathaan", 2023, "Siddharth Anand", "Shah Rukh Khan, Deepika Padukone, John Abraham, Dimple Kapadia",
     "Action, Spy, Thriller", 6.5, "spy, terrorism, comeback, mission, raw",
     "A rogue secret agent saves India from a deadly bioweapon attack."),
    ("Jawan", 2023, "Atlee", "Shah Rukh Khan, Nayanthara, Vijay Sethupathi, Deepika Padukone",
     "Action, Drama, Thriller", 7.0, "social justice, farmer, prison, mission, populist",
     "A prison warden leads a group of women to fight systemic corruption."),
    ("Animal", 2023, "Sandeep Reddy Vanga", "Ranbir Kapoor, Rashmika Mandanna, Anil Kapoor, Bobby Deol",
     "Action, Crime, Drama", 6.9, "father, obsession, violence, family, revenge",
     "A man's obsessive love for his father leads him down a violent path of revenge."),
    ("Rocky Aur Rani Kii Prem Kahaani", 2023, "Karan Johar", "Ranveer Singh, Alia Bhatt, Dharmendra, Jaya Bachchan",
     "Comedy, Drama, Romance", 6.8, "family, cultures, bengali, punjabi, love",
     "A Punjabi boy and Bengali girl discover love but must navigate their opposite families."),
    ("Fukrey", 2013, "Mrighdeep Singh Lamba", "Pulkit Samrat, Manjot Singh, Ali Fazal, Varun Sharma",
     "Comedy", 7.4, "lottery, college, comedy, dreams, scam",
     "Four losers in Delhi scam their way through life chasing money and success."),
    ("Chhello Show", 2021, "Pan Nalin", "Bhavin Rabari, Bhavesh Shrimali, Richa Meena, Dipen Raval",
     "Drama, Coming-of-Age", 8.0, "cinema, childhood, love for films, gujarat, innocence",
     "A 9-year-old boy discovers the magic of cinema and his life is changed forever."),
    ("Lust Stories", 2018, "Karan Johar", "Radhika Apte, Kiara Advani, Bhumi Pednekar, Manisha Koirala",
     "Drama, Romance", 7.3, "women, desire, anthology, modern india, relationships",
     "An anthology of four stories exploring desire and relationships among modern Indian women."),
    ("Geeli Pucchi", 2021, "Neeraj Ghaywan", "Konkona Sen Sharma, Aditi Rao Hydari",
     "Drama, Short", 8.1, "caste, lgbtq, workplace, discrimination, love",
     "Two women from different castes form an unexpected bond in a factory."),
]

# ─────────────────────────────────────────────
# Generate additional synthetic rows to pad to 120
# ─────────────────────────────────────────────
EXTRA_TITLES = [
    ("Hera Pheri", 2000, "Priyadarshan", "Akshay Kumar, Suniel Shetty, Paresh Rawal, Tabu",
     "Comedy", 8.2, "money, comedy, poor, kidnap, chaos",
     "Three broke men accidentally get caught up in a ransom demand that could make them rich."),
    ("Phir Hera Pheri", 2006, "Neeraj Vora", "Akshay Kumar, Suniel Shetty, Paresh Rawal, Bipasha Basu",
     "Comedy", 7.6, "sequel, investment, money, comedy, scam",
     "The trio from Hera Pheri fall for another get-rich-quick scheme."),
    ("Welcome", 2007, "Anees Bazmee", "Akshay Kumar, Anil Kapoor, Nana Patekar, Katrina Kaif",
     "Comedy, Action", 7.2, "gangster, comedy, dubai, love, family",
     "A man falls for a gangster's sister and must deal with her eccentric criminal family."),
    ("No Entry", 2005, "Anees Bazmee", "Salman Khan, Anil Kapoor, Fardeen Khan, Celina Jaitley",
     "Comedy", 6.8, "marriage, cheating, comedy, wives, husbands",
     "Three married men try to have extramarital affairs and get entangled in comic situations."),
    ("Andaz Apna Apna", 1994, "Rajkumar Santoshi", "Aamir Khan, Salman Khan, Raveena Tandon, Karisma Kapoor",
     "Comedy", 8.3, "classic comedy, rivalry, rich girl, con, gold",
     "Two aspiring young men try to woo a rich girl for her inheritance in comedic fashion."),
]

all_movies = MOVIES + EXTRA_TITLES


def generate_dataset() -> pd.DataFrame:
    """Build and return the full Bollywood dataset as a DataFrame."""
    rows = []
    for m in all_movies:
        title, year, director, cast, genre, rating, keywords, overview = m
        # Add slight noise to ratings to make visualisations richer
        jitter = round(np.random.uniform(-0.15, 0.15), 1)
        final_rating = min(10.0, max(1.0, round(rating + jitter, 1)))
        rows.append(
            {
                "title": title,
                "year": year,
                "director": director,
                "cast": cast,
                "genre": genre,
                "rating": final_rating,
                "keywords": keywords,
                "overview": overview,
                "poster_url": f"https://via.placeholder.com/120x180.png?text={title.replace(' ', '+')}",
            }
        )
    df = pd.DataFrame(rows)
    df = df.drop_duplicates(subset=["title"]).reset_index(drop=True)
    return df


if __name__ == "__main__":
    out_path = os.path.join(os.path.dirname(__file__), "data.csv")
    df = generate_dataset()
    df.to_csv(out_path, index=False)
    print(f"✅  Dataset saved → {out_path}  ({len(df)} movies)")
